<a href="https://colab.research.google.com/github/TejasKumarBoddu1/B8_PFDS_1489/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quetion 1

In [1]:
import numpy as np

In [2]:
marks = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [76, 80, 72],
    [89, 94, 91],
    [65, 70, 68]
])

In [3]:
print("Student Marks (2D Array):\n", marks)

Student Marks (2D Array):
 [[85 90 78]
 [92 88 95]
 [76 80 72]
 [89 94 91]
 [65 70 68]]


In [4]:
avg_marks = np.mean(marks, axis=1)
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)

In [5]:

print("\nAverage Marks per Student:", avg_marks)
print("Minimum Marks per Student:", min_marks)
print("Maximum Marks per Student:", max_marks)



Average Marks per Student: [84.33333333 91.66666667 76.         91.33333333 67.66666667]
Minimum Marks per Student: [78 88 72 89 65]
Maximum Marks per Student: [90 95 80 94 70]


In [6]:

print("\nMarks of 1st Student:", marks[0])
print("Marks of 3rd Student:", marks[2])



Marks of 1st Student: [85 90 78]
Marks of 3rd Student: [76 80 72]


In [7]:

above_80 = marks > 80
print("\nBoolean Mask (Scores > 80):\n", above_80)
print("\nStudents with Scores > 80:\n", marks[above_80])


Boolean Mask (Scores > 80):
 [[ True  True False]
 [ True  True  True]
 [False False False]
 [ True  True  True]
 [False False False]]

Students with Scores > 80:
 [85 90 92 88 95 89 94 91]


In [10]:
reshaped = marks.T
print("Subject-wise Performance \n", reshaped)


Subject-wise Performance 
 [[85 92 76 89 65]
 [90 88 80 94 70]
 [78 95 72 91 68]]


# Quetion 2

In [12]:
import pandas as pd

data = {
    "Name": ["Aarav", "Diya", "Karan", "Meera", "Rohit"],
    "ID": [101, 102, 103, 104, 105],
    "Department": ["HR", "IT", "Finance", "Marketing", "IT"],
    "Salary": [45000, 60000, 52000, 75000, 48000]
}

df = pd.DataFrame(data)
df


Name   ID Department  Salary
0  Aarav  101         HR   45000
1   Diya  102         IT   60000
2  Karan  103    Finance   52000
3  Meera  104  Marketing   75000
4  Rohit  105         IT   48000

In [18]:
high_salary = df[df["Salary"] > 50000]
print("Employees with Salary > 50,000:\n")
high_salary

Employees with Salary > 50,000:



Name   ID Department  Salary   Bonus    Total
1   Diya  102         IT   60000  6000.0  66000.0
2  Karan  103    Finance   52000  5200.0  57200.0
3  Meera  104  Marketing   75000  7500.0  82500.0

In [19]:
sorted_df = df.sort_values(by="Salary", ascending=False)
print("DataFrame Sorted by Salary (Descending):\n")
sorted_df

DataFrame Sorted by Salary (Descending):



Name   ID Department  Salary   Bonus    Total
3  Meera  104  Marketing   75000  7500.0  82500.0
1   Diya  102         IT   60000  6000.0  66000.0
2  Karan  103    Finance   52000  5200.0  57200.0
4  Rohit  105         IT   48000  4800.0  52800.0
0  Aarav  101         HR   45000  4500.0  49500.0

In [20]:
df["Bonus"] = df["Salary"] * 0.10
print("DataFrame with Bonus Column:\n")
df

DataFrame with Bonus Column:



Name   ID Department  Salary   Bonus    Total
0  Aarav  101         HR   45000  4500.0  49500.0
1   Diya  102         IT   60000  6000.0  66000.0
2  Karan  103    Finance   52000  5200.0  57200.0
3  Meera  104  Marketing   75000  7500.0  82500.0
4  Rohit  105         IT   48000  4800.0  52800.0

In [21]:
df["Total"] = df["Salary"] + df["Bonus"]
total_expense = df["Total"].sum()
print("Total Salary Expense (Including Bonuses):", total_expense)


Total Salary Expense (Including Bonuses): 308000.0
