In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[12,12,32],[44,15,63],[17,18,19]])
print("arr1+arr2")
print(arr1+arr2)
print("arr1-arr2")
print(arr1-arr2)
add=np.add(arr1,arr2)
print("add")
print(add)
sub=np.subtract(arr1,arr2)
print("sub")
print(sub)

arr1+arr2
[[13 14 35]
 [48 20 69]
 [24 26 28]]
arr1-arr2
[[-11 -10 -29]
 [-40 -10 -57]
 [-10 -10 -10]]
add
[[13 14 35]
 [48 20 69]
 [24 26 28]]
sub
[[-11 -10 -29]
 [-40 -10 -57]
 [-10 -10 -10]]


In [ ]:
import numpy as np

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])
dot = np.dot(arr3, arr4)
ans = arr3 @ arr4
print("Matrix A")
print(arr3)
print("Matrix B")
print(arr4)
print("dot")
print(dot)
print("ans")
print(ans)


Matrix A
[[1 2]
 [3 4]
 [5 6]]
Matrix B
[[ 7  8  9]
 [10 11 12]]
dot
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
ans
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


## creating file

In [ ]:
file=open("example.txt","w")
file.write("Hello ,Btech students!\n")
file.write("This is file handaling in python,\n")
file.write("SR University ")
file.close()
print("done")

done


##"Reading file"

In [ ]:
file=open("example.txt","r")
print(file.read())
file.close()

Hello ,Btech students!
This is file handaling in python,
SR University 


##Read line by line

In [ ]:
file=open("example.txt","r")
line1=file.readline()
print(line1)
line2=file.readline()
print(line2)
line3=file.readline()
print(line3)
file.close()


Hello ,Btech students!

This is file handaling in python,

SR University 


In [ ]:
file = open("example.txt","r")
lines = file.readlines()
print("all", lines)
file.close()


all ['Hello ,Btech students!\n', 'This is file handaling in python,\n', 'SR University appending new data\n']


In [ ]:
file = open("example.txt","a")
file.write("appending new data\n")
file.close()

In [ ]:
with open("example.txt","r") as file:
  data=file.read()
  print(data)


Hello ,Btech students!
This is file handaling in python,
SR University appending new data
appending new data



##create and write csv

In [ ]:
import csv
with open("data.csv","w",newline="") as file:
  writer=csv.writer(file)
  wr=csv.writer(file)
  wr.writerow(["Name","age","course"])
  wr.writerow(["a",18,"cse"])
  wr.writerow(["a",22,"cse"])
  wr.writerow(["a",31,"cse"])

##read csv

In [ ]:
with open("data.csv","r") as file:
  read=csv.reader(file)
  for row in read:
    print(row)

['Name', 'age', 'course']
['a', '18', 'cse']
['a', '22', 'cse']
['a', '31', 'cse']
